lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem'
    public_key: '%kernel.project_dir%/config/jwt/public.pem'
    pass_phrase: 'd9100837cccef94be85f8b3812f45993' # required for token creation, usage of an environment variable is recommended
    token_ttl: 600 #expires after 10 minutes